# Generated by Django 4.1.3 on 2023-04-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
