# Generated by Django 4.1.3 on 2023-04-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
